// Mocks generated by Mockito 5.4.6 from annotations
// in oping/test/workers/chapter_check_worker_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:oping/models/chapter.dart' as _i4;
import 'package:oping/services/chapter_storage_service.dart' as _i5;
import 'package:oping/services/manga_dex_service.dart' as _i2;
import 'package:oping/services/notification_service.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [MangaDexService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMangaDexService extends _i1.Mock implements _i2.MangaDexService {
  MockMangaDexService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Chapter?> fetchLatestChapter() =>
      (super.noSuchMethod(
            Invocation.method(#fetchLatestChapter, []),
            returnValue: _i3.Future<_i4.Chapter?>.value(),
          )
          as _i3.Future<_i4.Chapter?>);
}

/// A class which mocks [ChapterStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChapterStorageService extends _i1.Mock
    implements _i5.ChapterStorageService {
  MockChapterStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<double> getLastSeenChapter() =>
      (super.noSuchMethod(
            Invocation.method(#getLastSeenChapter, []),
            returnValue: _i3.Future<double>.value(0.0),
          )
          as _i3.Future<double>);

  @override
  _i3.Future<void> saveLastSeenChapter(double? chapterNumber) =>
      (super.noSuchMethod(
            Invocation.method(#saveLastSeenChapter, [chapterNumber]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<DateTime?> getLastChecked() =>
      (super.noSuchMethod(
            Invocation.method(#getLastChecked, []),
            returnValue: _i3.Future<DateTime?>.value(),
          )
          as _i3.Future<DateTime?>);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i6.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> showNewChapterNotification(_i4.Chapter? chapter) =>
      (super.noSuchMethod(
            Invocation.method(#showNewChapterNotification, [chapter]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
